# Generated by Django 5.0.6 on 2024-05-17 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('installed_at', models.DateTimeField(auto_now_add=True)),
                ('last_maintained_at', models.DateTimeField(auto_now=True)),
                ('equipment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.equipmenttype')),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('value', models.FloatField()),
                ('unit', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='monitoring.equipment')),
            ],
            options={
                'indexes': [models.Index(fields=['equipment', 'timestamp'], name='monitoring__equipme_8ca413_idx'), models.Index(fields=['name'], name='monitoring__name_73d1d2_idx')],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('severity', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=50)),
                ('description', models.TextField()),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='monitoring.equipment')),
            ],
            options={
                'indexes': [models.Index(fields=['equipment', 'timestamp'], name='monitoring__equipme_cbff59_idx'), models.Index(fields=['severity'], name='monitoring__severit_1dbc15_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['equipment_type'], name='monitoring__equipme_0cfd0c_idx'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['installed_at'], name='monitoring__install_76dde8_idx'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['status'], name='monitoring__status_c5d754_idx'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['serial_number'], name='monitoring__serial__868214_idx'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['last_maintained_at'], name='monitoring__last_ma_7b3176_idx'),
        ),
    ]
