# Generated by Django 5.0.6 on 2024-05-18 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='status',
            field=models.CharField(choices=[('IN_USE', 'In Use'), ('DISABLED', 'Disabled'), ('IN_REPAIR', 'In Repair')], max_length=50),
        ),
    ]
