# Generated by Django 5.0.6 on 2024-05-18 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_alter_equipment_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_performed', models.DateTimeField()),
                ('maintenance_type', models.CharField(choices=[('INSPECTION', 'Inspection'), ('REPAIR', 'Repair'), ('MINOR_SYSTEM_UPDATE', 'Minor System Update'), ('MAJOR_SYSTEM_UPDATE', 'Major System Update')], max_length=100)),
                ('notes', models.TextField()),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='monitoring.equipment')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
